### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by jasonkuhrt** [homer0/packages#17]
On latest version, when using Node 12:

```
❯ yarn -s prettier -h
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'comment-parser/lib'
Require stack:
- /Users/jasonkuhrt/projects/prisma/nexus-prisma/node_modules/@homer0/prettier-plugin-jsdoc/src/fns/getParsers.js
- /Users/jasonkuhrt/projects/prisma/nexus-prisma/node_modules/@homer0/prettier-plugin-jsdoc/src/fns/getPlugin.js
- /Users/jasonkuhrt/projects/prisma/nexus-prisma/node_modules/@homer0/prettier-plugin-jsdoc/src/index.js
- /Users/jasonkuhrt/projects/prisma/nexus-prisma/node_modules/prettier/index.js
- /Users/jasonkuhrt/projects/prisma/nexus-prisma/node_modules/prettier/bin-prettier.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/jasonkuhrt/projects/prisma/nexus-prisma/node_modules/@homer0/prettier-plugin-jsdoc/src/fns/getParsers.js:2:34)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jasonkuhrt/projects/prisma/nexus-prisma/node_modules/@homer0/prettier-plugin-jsdoc/src/fns/getParsers.js',
    '/Users/jasonkuhrt/projects/prisma/nexus-prisma/node_modules/@homer0/prettier-plugin-jsdoc/src/fns/getPlugin.js',
    '/Users/jasonkuhrt/projects/prisma/nexus-prisma/node_modules/@homer0/prettier-plugin-jsdoc/src/index.js',
    '/Users/jasonkuhrt/projects/prisma/nexus-prisma/node_modules/prettier/index.js',
    '/Users/jasonkuhrt/projects/prisma/nexus-prisma/node_modules/prettier/bin-prettier.js'
  ]
}
```

When using Node 16:

```
❯ yarn -s prettier -h
node:internal/modules/cjs/loader:482
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib' is not defined by "exports" in /Users/jasonkuhrt/projects/prisma/nexus-prisma/node_modules/comment-parser/package.json
    at new NodeError (node:internal/errors:363:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:335:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:560:3)
    at resolveExports (node:internal/modules/cjs/loader:476:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:516:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:913:27)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/jasonkuhrt/projects/prisma/nexus-prisma/node_modules/@homer0/prettier-plugin-jsdoc/src/fns/getParsers.js:2:34) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by jasonkuhrt** [comment]
Workaround for now 
<img width="252" alt="CleanShot 2021-07-27 at 15 36 22@2x" src="https://user-images.githubusercontent.com/284476/127216897-a5d566ce-dd22-4d55-ada6-f1735224b1f1.png">

**Comment by madebysid** [comment]
A more permanent solution for this could be freezing dependency versions in this package's `package.json`

**Comment by homer0** [comment]
I'll try to look into this today.

I'm not a fan of pinning versions :P; unless you convince the entire internet to do the same, it doesn't matter if your deps are pinned, if a module uses a SemVer range, you would potentially be installing something new either way. Also, that's why we have SemVer... but not everyone respects it.

Now, the last change I did was from `^1.1.4` to `^1.1.5`, and the last published version of `comment-parser` is `1.2.3`, so this was going to break regardless of my release: They pushed a breaking change as a fix.

I'll check if there's a fix or if they are working on it and if it will take too much time, I'll pin the dep for now.

**Comment by homer0** [comment]
@jasonkuhrt @madebysid Done :D, they changed from `.js` to `.cjs` for commonjs, it was just a matter to include the extension in the `require`. I created [an issue](https://github.com/syavorsky/comment-parser/issues/140) for them, so they're away.

This was closed automatically by GitHub when the PR was merged, but this is still happening, please reopen.

**Comment by homer0** [comment]
Update: Didn't work :P. When used as a dependency of a dependency (like when you use the plugin), since the `package.json` from `comment-parser` doesn't include `exports` for the `.cjs` files, it causes a new error.

Fck it... pinning it for now, you win this time @madebysid 🤣

**Comment by madebysid** [comment]
Haha thanks for taking care of this so quickly!
